import numpy as np
import cv2
img1=cv2.imread("opencv1.jpeg",-1)
img2=cv2.imread("12.jpg",-1)
print(img2.shape)
grayimg=cv2.cvtColor(img1,cv2.COLOR_BGR2GRAY)
cv2.imshow('grayscale',grayimg)
ret,mask=cv2.threshold(grayimg,230,255,cv2.THRESH_BINARY_INV)
cv2.imshow('mask',mask)
mask_inv=cv2.bitwise_not(mask)
cv2.imshow('mask_inv',mask_inv)
img2_bg=cv2.bitwise_and(img2,img2,mask=mask_inv)
cv2.imshow('img2_bg',img2_bg)
img1_fg=cv2.bitwise_and(img1,img1,mask=mask)
cv2.imshow('img1_fg',img1_fg)
final=cv2.add(img2_bg,img1_fg)
cv2.imshow('final',final)
cv2.waitKey(0)
cv2.destroyAllWindows()
